<?php

namespace App\Models;

use App\Events\SendMessage;
use App\Http\Resources\ChatResource;
use App\Validators\MessagesValidator;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Model;

class Chat extends Model
{
    protected $guarded=[];

    use SoftDeletes ,MessagesValidator ;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function fromUser()
    {
        return $this->belongsTo(User::class,'from_user_id','id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function toUser()
    {
        return $this->belongsTo(User::class,'to_user_id','id');
    }

    /**
     * @param $model
     */
    public function afterSave($model)
    {
        event(new SendMessage(new ChatResource($model)));
        parent::afterSave($model); // TODO: Change the autogenerated stub
    }
}
