<?php

namespace App\Models;
use App\Events\Contact;

class ContactUs extends Model
{
    //
    protected $fillable = [
        'id', 'subject', 'text','viewed'
    ];

    public function afterSave($model)
    {
        event(new Contact( $model ));
        parent::afterSave($model); // TODO: Change the autogenerated stub
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user ()
    {
        return $this->belongsTo(User::class,'user_id','id');
    }
}
